---

vimfiles_repo: "git://github.com/mtchavez/vimfiles.git"
vimfiles_dir: "{{ workspace_dir }}/vimfiles"
vimfiles_install_cmd: "./install.sh -u"
ycm_bundle_dir: "{{ home_dir }}/.vim/bundle/YouCompleteMe"
ycm_install_cmd: "./ycm-update.sh"
ycm_installed_file: "{{ home_dir }}/.ycm_installed"
macvim_install_options: ""
