---

- name: Install ASDF version manager
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_ver }}"
  tags:
    - asdf
    - packages

- name: Add global asdf config
  template:
    src: asdfrc.j2
    dest: "{{ asdf_global_config }}"
  tags:
    - asdf
    - packages
