---
- name: Install brew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ python_brew_packages }}"
  tags:
    - python
    - brew

- name: Install pipx
  homebrew:
    name: pipx
    state: latest
  tags:
    - python

- name: Install python packages
  pip:
    name: "{{ python_packages }}"
    state: latest
    executable: pip3
  tags:
    - python

- name: Install (or upgrade) Certbot in pipx
  command: >
    pipx install certbot --force
  args:
    # only run if the venv is missing
    creates: "{{ lookup('env','HOME') }}/.local/pipx/venvs/certbot"
  tags:
    - python

- name: Inject Gandi DNS plugin into Certbot venv
  command: >
    pipx inject certbot certbot-dns-gandi --include-deps --force
  tags:
    - python

- name: Install python versions via pyenv
  shell: "if [ ! `pyenv versions | grep {{ item }}` ]; then {{ python_pyenv_install_cmd }} {{ item }}; fi"
  with_items: "{{ python_pyenv_versions }}"
  when: python_use_pyenv != False
  tags:
    - python
