---

- name: Install golang via homebrew
  homebrew:
    name: go
    state: present
  tags:
    - brew
    - golang

- name: Go path dirs
  file:
    path: "{{ gopath_dir }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ staff_group }}"
    state: directory
  with_items:
    - src
    - pkg
    - bin
  tags:
    - golang

- name: Install golang packages
  command: "go install {{ item }}@latest"
  with_items: "{{ golang_default_packages }}"
  ignore_errors: yes
  tags:
    - golang
    - godep
    - dependencies
