---
brew_install_cmd: 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
brew_base_packages:
  - name: artginzburg/tap/sudo-touchid
  - name: asdf
  - name: atuin
  - name: autoconf
  - name: automake
  #  - name: bash
  #  - name: bash-completion
  #  - name: bat
  #  - name: bazaar
  - name: cc65
  #  - name: cmake
  #  - name: coreutils
  #  - name: cscope
  #  - name: ctags
  #  - name: curl
  #  - name: direnv
  - name: eza
  #  - name: exercism
  - name: ffmpeg
  #  - name: findutils
  #  - name: fn
  #  - name: fontconfig
  #  - name: freetype
  #  - name: fswatch
  - name: fzf
  #  - name: gettext
  #  - name: git
  #  - name: git-duet
  #  - name: git-extras
  #  - name: git-lfs
  #  - name: git-secrets
  - name: gmp
  #  - name: goenv
  #  - name: gnu-sed
  #  - name: gnu-tar
  #  - name: graphviz
  #  - name: hadolint
  #  - name: hashicorp/tap/waypoint
  #  - name: heroku
  #  - name: hub
  - name: hudochenkov/sshpass/sshpass
  - name: hugo
  #  - name: inetutils
  #  - name: jenv
  - name: jq
  #  - name: kubectl
  #  - name: libevent
  #  - name: libffi
  #  - name: libidn
  #  - name: libmemcached
  #  - name: libmpc
  #  - name: libpng
  #  - name: libxml2
  - name: libyaml
  #  - name: lorem
  #  - name: lua
  - name: lua-language-server
  #  - name: makedepend
  #  - name: memcached
  #  - name: mercurial
  #  - name: moreutils
  - name: neovim
  #  - name: nomad
  - name: openssl
    #  - name: packer
  - name: prettier
  #  - name: protobuf
  #  - name: reattach-to-user-namespace
  #  - name: readline
  - name: ripgrep
  #  - name: s3cmd
  - name: shellcheck
  #  - name: snappy
  #  - name: sqlite
  - name: starship
  - name: stylua
  - name: synchronal/tap/medic
  - name: synchronal/tap/medic-ext-elixir
  - name: synchronal/tap/medic-ext-git
  - name: synchronal/tap/medic-ext-homebrew
  - name: synchronal/tap/medic-ext-node
  - name: synchronal/tap/medic-ext-rust
  - name: synchronal/tap/medic-ext-tool-versions
  - name: synchronal/tap/medic-ext-postgres
  - name: taplo
  #  - name: terraform
  #  - name: thefuck
  #  - name: the_silver_searcher
  #  - name: tmate
  - name: tree
  - name: tmux
  #  - name: vault
  - name: vice
  - name: viu
  #  - name: watchman
  #  - name: wget
  #  - name: yarn
  - name: yamllint
  - name: zoxide
brew_cask_applications:
  - name: 1password
  #  - name: alfred
  #  - name: appzapper
  #  - name: arduino
  #  - name: atom
  #  - name: bartender
  #  - name: caffeine
  - name: chatgpt
  - name: chromedriver
  - name: claude
  - name: cursor
  - name: figma
  - name: firefox
  #  - name: firefox-developer-edition
  #  - name: flux
  - name: ghostty
  - name: google-chrome
  #  # TODO: Requires password, become sudo
  #  - name: gpg-suite
  #  - name: imagealpha
  #  - name: imageoptim
  #  - name: istat-menus
  #  - name: iterm2
  #  - name: keybase
  #  - name: little-snitch
  #  - name: nordvpn
  - name: rectangle-pro
  - name: rubymine
  - name: sonos
  - name: spotify
  #  - name: sublime-text
  - name: telegram
  #  - name: the-unarchiver
  #  - name: tor-browser
  #  - name: tunnelblick
  #  - name: tuple
  #  - name: vagrant
  #  # NOTE: has needs for Apple silicon
  # - name: virtualbox
  #  - name: viscosity
  - name: visual-studio-code
  #  - name: vmware-fusion
  #  - name: vlc
  #  - name: whatsapp
  - name: zoom
brew_taps:
  - name: artginzburg/tap
  - name: hudochenkov/sshpass
  #  - name: git-duet/tap
  #  - name: homebrew/cask-versions
  #  - name: heroku/brew
  #  - name: hashicorp/tap
  - name: synchronal/tap
