#!/usr/bin/env bash
#
# Provision script for Ansible playbooks
#

# Ensure correct PATHs
PATH=/usr/local/bin:/opt/homebrew/bin:$PATH

# Activate the virtual environment
venv_dir="ansible_venv"
if [ -d "$venv_dir" ]; then
    # shellcheck disable=SC1091
    source "${venv_dir}/bin/activate"
else
    echo "Error: Virtual environment not found in ${venv_dir}. Please run the bootstrap script first."
    exit 1
fi

# Get Python version details (not strictly necessary here but retained)
version=$(python3 --version | awk '{ print $2 }')
major=$(echo "$version" | cut -d. -f1)
minor=$(echo "$version" | cut -d. -f2)
PATH=$HOME/Library/Python/"${major}.${minor}"/bin:$PATH

# Run the Ansible playbook
time ansible-playbook --diff --ask-become-pass "$@"

# vim: ft=sh: