---
ruby_global_version: "3.4.1"
ruby_default_gems_file: "{{ home_dir + '/.default-gems' }}"
ruby_versions:
  - "{{ ruby_global_version }}"
  - "3.3.7"
ruby_default_gems:
  - bundler
  - bundler-audit
  - rake
  - reek
  - ripper-tags
  - rubocop
  - solargraph
