---

- name: Check for ruby plugin
  command: "asdf plugin-list"
  register: asdf_plugins
  tags:
    - ruby
    - asdf-plugin

- name: Add asdf ruby plugin
  command: "asdf plugin-add ruby"
  when: "'ruby' not in asdf_plugins.stdout"
  tags:
    - ruby
    - asdf-plugin

- name: Write default-gem file
  template:
    src: default-gems.j2
    dest: "{{ ruby_default_gems_file }}"
  tags:
    - ruby
    - asdf-plugin
    - dependencies
    - gems

- name: Install ruby versions
  command: "asdf install ruby {{ item }}"
  args:
    creates: "{{ home_dir }}/.asdf/installs/ruby/{{ item }}"
  with_items: "{{ ruby_versions }}"
  tags:
    - ruby
    - asdf-plugin

- name: Set global ruby version
  command: "asdf global ruby {{ ruby_global_version }}"
  tags:
    - ruby
    - asdf-plugin

- name: Install ruby gems
  gem:
    name: "{{ item }}"
  with_items: "{{ ruby_default_gems }}"
  ignore_errors: true
  tags:
    - ruby
    - dependencies
    - gems
